Fix C++ compile error C2065: '_alloca' : undeclared identifier
When compiling in C++ mode, it is required to have C declaration for
_alloca. Declaration can be included also via malloc.h header file.