Fix test compile error C2065: 'errno' : undeclared identifier
For errno usage it is required to include C header file errno.h and do not
depend that some other header file will include it.